# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoaPodsSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaPodsSample
  pod 'Alamofire' # ここを追加!
end
